services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: school
      MYSQL_USER: user
      MYSQL_PASSWORD: password123
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql://user:password123@db:3306/school"
    ports:
      - "3000:3000"
    restart: always

volumes:
  mysql-data:
