# docker-compose.yml
version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: class-api-db
    restart: always
    environment:
      MYSQL_DATABASE: school
      MYSQL_USER: user
      MYSQL_PASSWORD: password123
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  app:
    build: .
    container_name: class-api
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/usr/src/app

volumes:
  db-data:
